apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    env: test-env
spec:
  containers:
  - name: mysql
    image: mysql:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "128Mi"
        cpu: "1"
      limits:
        memory: "512Mi"
        cpu: "2"
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "backend"
    effect: "NoSchedule"

