apiVersion: v1
kind: Pod
metadata:
  name: nginx-log
spec:
  containers:
  - name: app
    image: nginx:latest
    ports:
      - containerPort: 80
    env:
      - name: pod_name
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
    volumeMounts:
    - mountPath: /app_logs
      name: app-logs
      subPathExpr: $(pod_name)
  volumes:
  - name: app-logs
    hostPath:
      path: /var/log/app_logs
      type: DirectoryOrCreate
   
